apiVersion: v1
kind: Service
metadata:
  name: motivation-service
spec:
  selector:
    app: motivation
  type: NodePort            # <-- change from LoadBalancer to NodePort
  ports:
    - port: 5000            # container port
      targetPort: 5000
      nodePort: 30031       # any port between 30000-32767

